#!/bin/bash
#texts to be translated
#index.sh.htm
#Locale
export TEXTDOMAINDIR="/usr/share/locale"
export TEXTDOMAIN=om-control-center
#
hi=$"Hi"
title=$"OpenMandriva Control Center"
#Name=$"OpenMandriva Control Center"
#sections menu
menuindex=$"Welcome"
menusw=$"Software"
menuhardware=$"Hardware"
menuhardware2=$"Devices Configurations"
menulocaldisk=$"Local Disk configuration"
menunetwork=$"Networks"
menushare=$"Network Sharing"
menunetserv=$"Network servers"
menusystem=$"System"
menudesktop=$"Desktop"
menusecurity=$"Security"
menuabout=$"About"
#
#section presentation text
text=$"OpenMandriva Control Center is a set of tools to help you to configure your system, in each its part.
All in the same place and in the easiest way possible: <br/>
In each section you will find the programs to configure: <br/>
- Software Management<br/>
- Hardware<br/>
- Network, Internet & Sharing<br/>
- Local Disks/Partition Manager<br/>
- System Security<br/>
- ans other parts of your system.<br/>"
# OpenMandriva Control Center
# Sections and sub-Sections
#
#
#section 01 sw-management
titlepage01=$"Software and media management"
#01-Install & Remove software
titlednfdragora=$"Install additional applications with dnfdragora"
descdnfdragora=$"Find and install applications available in the repositories"
#01-Edit media Sorces
titleeditmedia=$"Add Media"
descaddmedia=$"Repository management, add new media"
#01-add 32bit support Sorces
titlerepo32bit=$"Add 32bits repositories"
descrepo32bit=$"Add the 32 bits repositories on a 64 bit architecture for the back compatibility"
#01-System update
titleupdate=$"Update of"
descupdate=$"To get the latest bug fixes and enhancements for your system"
#01-KBackup
titleunusedpackage=$"Remove Unused Packages"
descunusedpackage=$"Remove unused packages such as unused localization and unused hardware packages"
titlekbackup=$"KBackup"
desckbackup=$"Backup your data with an easy to use user interface"
titlekdiskfree=$"KDiskFree"
desckdiskfree=$"Displays information about hard disks and other storage devices"
#
#section 02 Hardware
titlepage02=$"Devices Configurations"
#02-Configure video
titlexfdrake=$"Display and Monitor"
descxfdrake=$"Manage and configure monitor and display"
#02-Configure printer
titleconfigprint=$"Configure your printer"
descconfigprint=$"Configure your printer, add drivers for HP, EPSON, etc"
#02-DVB devices
titledrakdvb=$"Configure your dvb devices"
descdrakdvb=$"Install all the necessary dirver to use your dvb devices"
#02-UPS devices
titledrakups=$"Configure an UPS"
descdrakups=$"Install all the necessary program to manage and configure your UPS"
#
#section 02B local Disk configuration
titlepage06=$"Local Disk Configurations"
#02B-disk management
titlediskdrake=$"Configure your local drives"
descdiskdrake=$"Change, configure and manage your local drives";
#
#section 03 Networks
titlepage03=$"Nertworks Configurations"
#03-Configure LAN
titleconfiglan=$"Configure the network"
descconfiglan=$"All the necessary tools to change or settings your networks, such as configuring static IP, PPPoE, 3G, etc"
#03-Configure hosts
titledrakhosts=$"Add network hosts "
descdrakhosts=$"Add all the known hosts of your network "
#03-Configure hostname
titlehostname=$"Change the hostname "
deschostname=$"Change the name of your computer, or set particular DNS"
#03-Configure internet Sharing
titledrakgw=$"Configure internet Sharing"
descdrakgw=$"Share your internet connection"
#03-Configure a proxy
titledrakproxy=$"Configure a proxy "
descdrakproxy=$"If you are into a company network, probably you should set the right proxy"
#03-Configure a VPN
titledrakvpn=$"Configure a VPN"
descdrakvpn=$"All the necessary to create and manage a VPN"
#
#section 03B sharing Configurations
titlepage05=$"Directory sharing configurations"
#03B-nfs
titledraknfs=$"Configure a NFS share"
descdraknfs=$"Change or configure your NFS directory scharing";
#03B-samba
titledraksambashare=$"Configure a SMB share"
descdraksambashare=$"Change or configure your SMB directory scharing";
#03C-servproftp
titleservproftp=$"Configure a FTP Server"
descservproftp=$"Install and configure your FTP server"
#03C-servopenssh
titleservopenssh=$"Configure a SSH Server"
descservopenssh=$"Install and configure a SSH server"
#03C-servapache
titleservapache2=$"Configure an Apache2 Server"
descservapache2=$"Install and configure your http server"
#03C-servdhcp
titleservdhcp=$"Configure a DHCP Server"
descservdhcp=$"Install and configure your DHCP server"
#03C-servdnsbind
titleservdnsbind=$"Configure a DNS Server"
descservdnsbind=$"Install and configure your DNS server"
#03C-servtimentp
titleservtimentp=$"Configure a TIME Server"
descservtimentp=$"Install and configure your NTP server"
#
#section 04 System Configurations
titlepage04=$"System Configurations"
#04-Add & Configure user and groups
titledrakuser=$"Add & Configure user and groups"
descdrakuser=$"Here you can configure new users add groups etc"
#04-Services management
titleservices=$"Services management"
descservices=$"Start and stop of the entire services available on the system"
#04-Add fonts
titledrakfont=$"Add other fonts"
descdrakfont=$"Add new set of fonts"
#04-Configure time
titledrakclock=$"Configure time"
descdrakclock=$"Change time, configure the nts"
#04-Configure DM
titledrakedm=$"Change the Display Manager"
descdrakedm=$"Change the display manager that you use (KDM, GDM)"
#04-Configure Keyboard
titlekeyboard=$"Configure keyboard"
desckeyboard=$"Change or configure keyboard layout"
#
#04-Themes management
titlechangethemes=$"Configure a theme "
descchangethemes=$"Install or change theme "
#04-Change icons theme
titlechangeicons=$"Configure Desktop Icons"
descchangeicons=$"Change or configure your desktop icons or install your favorite icons"
#04-boot configuration
titleconfigboot=$"Configure the system boot"
descconfigboot=$"If you need to change the boot order of the system or repair grub2 manually or later add another operating system"
#
#section 05 Security
titlepage07=$"Security Configurations"
#05-Security management
titlefirewall=$"Configure your firewall"
descfirewall=$"Change, configure and manage your firewall settings";
#05-firewall applet
titlefirewall2=$"Open your firewall applet"
descfirewall2=$"Change, configure and manage your firewall settings from the applet";
#04-Autorization management
titledraksec=$"Autorization management"
descdraksec=$"Configure users Autorization to the OpenMandriva configuration tools"

#About.sh.htm
about=$"About "
license=$"This software is licensed under the GNU General Public License version 2 (GPLv2)."
dependency=$"It uses Qt5 WebEngine and htmlscript."
bugs=$"For bugs, suggestions and improvements, please head to "
endapp=$"Exit"
#Additional
you_are_using=$"You are using"
with_kernel=$"with kernel"
arch=$"architecture"
next=$"Next"

